val=int(input('Digite um número: '))

print('_____________')
print('{} X {} = {}'.format(val, '00', val*0))
print('{} X {} = {}'.format(val, '01', val*1))
print('{} X {} = {}'.format(val, '02', val*2))
print('{} X {} = {}'.format(val, '03', val*3))
print('{} X {} = {}'.format(val, '04', val*4))
print('{} X {} = {}'.format(val, '05', val*5))
print('{} X {} = {}'.format(val, '06', val*6))
print('{} X {} = {}'.format(val, '07', val*7))
print('{} X {} = {}'.format(val, '08', val*8))
print('{} X {} = {}'.format(val, '09', val*9))
print('{} X {} = {}'.format(val, '10', val*10))
print('_____________')